Revert "Windows: Bump Erlang/OTP version to 28.x"
This reverts commit 56ccd5ccb0339d927b7e8bdd85a041afd4280d0a.

It seems that our environment variable for setting the -I paths is
ignored when using port_compiler with Erlang/OTP 28:

| Compiling d:/a/eturnal/eturnal/c_src/fast_tls.c
| d:/a/eturnal/eturnal/c_src/fast_tls.c:21:10: fatal error: openssl/err.h: No such file or directory

We should probably specify the 'port_env' variable as documented here:

https://github.com/blt/port_compiler?tab=readme-ov-file#example

I.e., something along the lines of:

| {port_env, [
|     {"win32", "CFLAGS", "$CFLAGS -I" ++ os:getenv("CFLAGS")},
|     {"win32", "LDFLAGS", "$LDFLAGS -L" ++ os:getenv("LDFLAGS")}
| ]}.

But for the moment, let's just revert to Erlang/OTP 27.