ci/macos: run with macos-13
Running with macos-latest (14) fails, because 

===> /Users/runner/work/eturnal/eturnal/c_src/fast_tls.c:21:10: fatal error: 'openssl/err.h' file not found

Difference: Intel vs. AppleM1 , so we need to understand which paths/variables to set. Afterwards we revert back to macos-latest (14).